server/db/models/order.js
server/db/models/productOrder.js

created Models orders and ProductOrder in respective js files

---

server/db/models/user.js

userModel update

---

server/db/models/index.js
server/db/models/order.js
server/db/models/productOrder.js

created associations between User, Order, Products, and Order

---

server/db/models/shoppingCart.js
server/db/models/shoppingCartDetails.js

Shopping cart

---

server/db/models/index.js
server/db/models/paymentMethod.js
server/index.js

created paymentMethod table and made associations

---

script/seed.js
server/api/users.spec.js
server/db/models/product.spec.js
server/db/models/products.js
server/db/models/user.spec.js

chore: created 2 test specs

---

script/seed.js
server/db/models/shoppingCartDetails.js

dummy data to seed db

---

client/app.js
client/components/navbar.js
public/index.html
public/style.css
server/index.js

styling for homepage css & HTML

---

client/components/SingleProduct.js
client/components/navbar.js
client/index.js
script/seed.js
server/api/cart.js
server/api/index.js
server/db/models/order.js
server/db/models/paymentMethod.js

slight updates to user store

---

client/app.js
client/components/SingleProduct.js
client/store/actioncreators.js
client/store/index.js
client/store/reducers.js
client/store/user.js
server/api/cart.js

User cart mount

---

client/app.js
client/components/SingleCategory.js
server/api/users.js
server/auth/protector.js
server/db/models/order.js
server/db/models/orderProduct.js
server/db/models/product.js

subtotal getter method added

---

client/components/Cart.js
client/components/navbar.js
client/store/user.js

Cart component should show an empty cart if no cart state is empty.
---

Remove item feature

---

client/app.js
client/components/SingleCategory.js
client/components/navbar.js
client/routes.js
client/store/user.js

fix user cart persistence for when user first logs in
select products renders correctly

fix user cart persistence

---

client/app.js
client/components/Cart.js
client/components/QuantityButton.js
client/components/SingleProduct.js
server/api/cart.js

added functionality for removing a user's cart item in cart component
added functionality for updating a user's cart item in cart component
calculate subtotals on each update/removal
calculate total price on each update/removal

Remove Item Button and Update Quantity Button

---

client/components/admin.js
client/components/allproducts.js
client/components/navbar.js
client/index.js
public/style.css
script/seed.js
server/api/products.js

-admin page 
-can delete or add quantity to inventory
-need to finalize autorender and styling & update protection

isAdmin page update

---

client/components/Cart.js
client/components/Checkout.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/GuestCompleteOrder.js
client/components/QuantityButton.js
client/components/SingleProduct.js
client/index.js
server/api/checkout.js

- Added Guest Checkout Component - select payment method and place order button
Clicking order button will update OrderProduce table with relevant data and also create an OrderId for the guest (however, userId in the Order table will be null, no way of identifying past guest orders)
- Added Guest Complete Order - page to show guest order's ID and other future data needed.

Guest cart

---

client/components/NewUser.js
client/components/SignupForm.js
client/components/auth-form.js
client/index.js
public/style.css
server/api/users.js
server/db/models/user.js

Signup branch

---

client/components/allproducts.js
client/components/allusers.js
client/index.js
client/store/actioncreators.js
client/store/index.js
client/store/reducers.js
public/style.css
server/api/users.js

slight updates to admin page

---

client/store/user.spec.js
server/api/products.spec.js
server/api/users.spec.js
server/db/models/associations.spec.js
server/db/models/order.spec.js
server/db/models/product.spec.js

new test specs

---

client/app.js
client/components/Cart.js
client/components/Checkout.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/QuantityButton.js
client/components/SingleProduct.js
server/api/cart.js

deleted console logs, alerts, added css styles

---

client/app.js
client/components/Cart.js
client/components/Checkout.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/HomePage.js
client/components/NewUser.js
client/components/SingleCategory.js
client/components/allproducts.js
client/index.js

changed app.js/index.js structure created homePage component

---

client/app.js
client/components/Cart.js
client/components/Checkout.js
client/components/GuestCart.js
client/components/GuestCheckout.js
client/components/HomePage.js
client/components/SingleCategory.js
client/components/SingleProduct.js
client/store/actioncreators.js
client/store/reducers.js
public/style.css
server/api/cart.js

Cart slice code improv
